tunnel: crmgeofal-backend
credentials-file: C:\Users\Lenovo\.cloudflared\crmgeofal-backend.json

ingress:
  - hostname: crmgeofal-backend.trycloudflare.com
    service: http://localhost:4000
  - service: http_status:404
